//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/Home/FollowPromptInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @FollowPromptInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @FollowPromptInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""FollowPromptInput"",
    ""maps"": [
        {
            ""name"": ""Home"",
            ""id"": ""6438316c-a62f-47e1-8356-c6665300ec13"",
            ""actions"": [
                {
                    ""name"": ""FollowPrompt"",
                    ""type"": ""Button"",
                    ""id"": ""f28d03ac-0dca-4beb-b816-3c4b6e26a8c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f77d0313-97aa-46f4-a543-71e881c4bf16"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FollowPrompt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Home
        m_Home = asset.FindActionMap("Home", throwIfNotFound: true);
        m_Home_FollowPrompt = m_Home.FindAction("FollowPrompt", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Home
    private readonly InputActionMap m_Home;
    private List<IHomeActions> m_HomeActionsCallbackInterfaces = new List<IHomeActions>();
    private readonly InputAction m_Home_FollowPrompt;
    public struct HomeActions
    {
        private @FollowPromptInput m_Wrapper;
        public HomeActions(@FollowPromptInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @FollowPrompt => m_Wrapper.m_Home_FollowPrompt;
        public InputActionMap Get() { return m_Wrapper.m_Home; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HomeActions set) { return set.Get(); }
        public void AddCallbacks(IHomeActions instance)
        {
            if (instance == null || m_Wrapper.m_HomeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HomeActionsCallbackInterfaces.Add(instance);
            @FollowPrompt.started += instance.OnFollowPrompt;
            @FollowPrompt.performed += instance.OnFollowPrompt;
            @FollowPrompt.canceled += instance.OnFollowPrompt;
        }

        private void UnregisterCallbacks(IHomeActions instance)
        {
            @FollowPrompt.started -= instance.OnFollowPrompt;
            @FollowPrompt.performed -= instance.OnFollowPrompt;
            @FollowPrompt.canceled -= instance.OnFollowPrompt;
        }

        public void RemoveCallbacks(IHomeActions instance)
        {
            if (m_Wrapper.m_HomeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHomeActions instance)
        {
            foreach (var item in m_Wrapper.m_HomeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HomeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HomeActions @Home => new HomeActions(this);
    public interface IHomeActions
    {
        void OnFollowPrompt(InputAction.CallbackContext context);
    }
}
